### ISSUE TITLE
KittiSeg_pretrained.zip

### ISSUE THREAD

**Issue by hongq123** [SummerHuiZhang/KittiSeg_Test#1]
Hello! The KittiSeg_pretrained model in the code has failed. Can you give me some information? 2018202110003@whu.edu.cn, thank you very much!

**Comment by SummerHuiZhang** [comment]
Sorry for late reply. I have contact you through Email

**Comment by hongq123** [comment]
> Hello! The KittiSeg_pretrained model in the code has failed. Can you give me some information? [2018202110003@whu.edu.cn](mailto:2018202110003@whu.edu.cn), thank you very much!
